[jobs.run-long]
command = [
  "cargo",
  "run",
  "--release"
  # put launch parameters for your program behind a `--` separator
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[jobs.run-long-dev]
command = [
  "cargo",
  "run",
  # put launch parameters for your program behind a `--` separator
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
