services:
  emitter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JEMALLOC_SYS_WITH_MALLOC_CONF: "background_thread:true,narenas:1,tcache:false,dirty_decay_ms:1,muzzy_decay_ms:1,abort_conf:true,retain:false"
    ports:
      - "8080:8080"
